[package]
name = "wsfl"
version = "0.1.0"
authors = ["Wang Jiang <sillyemperor@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sha2 = "0.8.0"
crossbeam = "0.7.2"


